//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 发行日志
        ///
        ///可以将此内容读取显示在界面上 的本地化字符串。
        /// </summary>
        internal static string ReleaseNote {
            get {
                return ResourceManager.GetString("ReleaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;InstallTitle&quot;:&quot;自定义安装包演示_安装程序&quot;,
        ///    &quot;UnInstallTitle&quot;:&quot;自定义安装包演示_卸载程序&quot;,
        ///    &quot;Icon&quot;:&quot;logo.png&quot;,
        ///    &quot;ReleaseNoteTitle&quot;:&quot;版本发行日志&quot;,
        ///    &quot;InstallPath&quot;:&quot;C:\\&quot;,
        ///    &quot;InstallerName&quot;:&quot;自定义安装包演示.exe&quot;,
        ///    &quot;CreateDesktopShortcut&quot;:true,
        ///    &quot;CreateStartup&quot;:true,
        ///    &quot;CreateDirectory&quot;:[
        ///        &quot;安装程序创建的目录1&quot;,
        ///        &quot;安装程序创建的目录2&quot;,
        ///        &quot;安装程序创建的目录3&quot;,
        ///        &quot;安装程序创建的目录4&quot;
        ///    ],
        ///    &quot;ShortcutItems&quot;:[
        ///        {
        ///            &quot;Name&quot;:&quot;CustomInstaller.exe&quot;,
        ///            &quot;Args&quot;:&quot;&quot;
        ///        }
        ///    ],
        ///    &quot;S [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SetupConfig {
            get {
                return ResourceManager.GetString("SetupConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] SetupFiles {
            get {
                object obj = ResourceManager.GetObject("SetupFiles", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
